export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const USER = "USER";

export const GET_ROLES = "GET_ROLES"
export const GETALLROLES = "GETALLROLES";

export const GET_ALL_PROGRAMMES = "GET_ALL_PROGRAMMES";
export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";

export const GET_ALL_REGIONAL_CENTRES = "GET_ALL_REGIONAL_CENTRES";
export const GET_ALL_STUDY_CENTRES = "GET_ALL_STUDY_CENTRES";

export const GET_ALL_INFORMATION = "GET_ALL_INFORMATION";

export const GET_ALL_USERS = "GET_ALL_USERS";